language: node_js
node_js: 
  - "stable"
install:
- npm install -g codecov
- npm install
script:
- npm run test
after_success:
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
notifications:
  email: false
deploy:
  provider: heroku
  api_key: f276c9b4-95a2-42c2-922e-0cac71b85c44
  app: melisharedserver
