language: node_js
node_js: 
  - "stable"
install:
- npm install -g codecov
- npm install
script:
- npm run test
after_success:
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
notifications:
  email: false
deploy:
  provider: heroku
  api_key: 5dd5ec87-7f48-448a-a1ed-cae25655043c
  app: melisharedserver
